---
version: 2
jobs:
  build-and-test:
    docker:
      - image: node:latest
    working_directory: ~/pear
    steps:
      - checkout

      - restore_cache:
          name: Restore yarn cache
          key: yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn install
          command: yarn install

      - save_cache:
          name: Save yarn cache
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

      - run:
          name: Get version
          command: ./bin/run --version

      - run:
          name: Show help
          command: ./bin/run --help

      - run:
          name: Run tests
          command: yarn test

workflows:
  version: 2
  pear:
    jobs:
      - build-and-test
